# Generated by Django 5.1.1 on 2024-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
